[PATCH] Port one/one_udp.c to Linux 4.1
Kernel commit c0371da6047a replaced msg_iov and msg_iovlen with msg_iter
in struct msghdr since 3.19

one/one_udp.c: In function 'ksocket_send_iov':
one/one_udp.c:186:9: error: 'struct msghdr' has no member named 'msg_iov'
one/one_udp.c:187:9: error: 'struct msghdr' has no member named
'msg_iovlen'

one/one_udp.c: In function 'ksocket_receive':
one/one_udp.c:221:9: error: 'struct msghdr' has no member named 'msg_iov'
one/one_udp.c:222:9: error: 'struct msghdr' has no member named
'msg_iovlen'

The iov_iter interface
https://lwn.net/Articles/625077/

Kernel commit d8725c86aeba dropped the len parameter in sock_sendmsg
since 4.1

one/one_udp.c: In function 'ksocket_send_iov':
one/one_udp.c:192:13: error: too many arguments to function 'sock_sendmsg'

Signed-off-by: Marc Gonzalez <marc_gonzalez@sigmadesigns.com>

Kernel commit 2da62906b1e29 dropped the size parameter in sock_recvmsg
since 4.7

In function 'ksocket_receive'
one/one_udp.c:235:13: error: too many arguments to function 'sock_recvmsg'

Signed-off-by: Matthew Shyu <matthew.shyu@amlogic.com>